FROM amazonlinux:2017.03
MAINTAINER Ben Jones <ben@fogbutter.com>

ARG PYTHON_VERSION=3.6.2

# Install nessecary OS packages
RUN yum install -y gcc openssl-devel

# Download/build/install Python
RUN cd /usr/local/src &&\
    curl -O https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz &&\
    tar -xzf Python-${PYTHON_VERSION}.tgz &&\
    cd Python-${PYTHON_VERSION} && ./configure && make && make altinstall &&\
    python3.6 -m ensurepip && pip3.6 install pytest peewee





