version: 2
jobs:
  build:
    docker:
      - image: docker:stable-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build image
          command: docker build -t tempimage .
      - run:
          name: collect psycopg
          command: |
            mkdir -p workspace
            docker run --name tempcontainer tempimage /bin/true
            docker cp tempcontainer:/usr/local/src/psycopg2-2.7.3.1/build/lib.linux-x86_64-3.6/psycopg2 workspace
            docker rm tempcontainer
      - persist_to_workspace:
          root: workspace
          paths:
            - psycopg2

  test:
    docker:
      - image: realsalmon/amazonlinux-python
        environment:
          PGHOST: 127.0.0.1
      - image: postgres:9.6
    steps:
      - checkout
      - attach_workspace:
          at: tests
      - run:
          name: install required packages
          command: /venv/bin/pip install pytest peewee
      - run:
          name: run tests
          command: /venv/bin/pytest tests

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
      - test:
          requires:
            - build
